/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hickys
 */
public class AdicionarFilmeTela extends javax.swing.JFrame {
    
    public String emailCache;
    
    /**
     * Creates new form AdicionarFilmeTela
     */
    public AdicionarFilmeTela() {
        initComponents();
        listarFilmesTabela();
        listarCinemasTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dataLancamentoTextField = new javax.swing.JTextField();
        nomeFilmeTextField = new javax.swing.JTextField();
        emCartazTextField = new javax.swing.JTextField();
        sinopseTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        filmeTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cinemaTable = new javax.swing.JTable();
        voltarBtn = new javax.swing.JLabel();
        cadastrarBtn = new javax.swing.JLabel();
        excluirBtn = new javax.swing.JLabel();
        alterarBtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idCinemaTextField = new javax.swing.JTextField();
        idFilmeTextField = new javax.swing.JTextField();
        designarBtn = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dataLancamentoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Lançamento:"));
        jPanel1.add(dataLancamentoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, -1));

        nomeFilmeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("NomeFilme"));
        nomeFilmeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFilmeTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nomeFilmeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 250, -1));

        emCartazTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Em cartaz:"));
        jPanel1.add(emCartazTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, -1));

        sinopseTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Sinopse:"));
        sinopseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinopseTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(sinopseTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 250, 150));

        idTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("id"));
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 250, -1));

        filmeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome Filme", "Data Lançamento", "Cartaz"
            }
        ));
        jScrollPane1.setViewportView(filmeTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 350));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filmes:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cinema:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        cinemaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdCinema", "NomeCinema", "Localização"
            }
        ));
        jScrollPane2.setViewportView(cinemaTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, 190));

        voltarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltarTelas.png"))); // NOI18N
        voltarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                voltarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                voltarBtnMouseExited(evt);
            }
        });
        jPanel1.add(voltarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, -1, 30));

        cadastrarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastrarFilm.png"))); // NOI18N
        cadastrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarBtnMouseExited(evt);
            }
        });
        jPanel1.add(cadastrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        excluirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/excluirFilm.png"))); // NOI18N
        excluirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                excluirBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                excluirBtnMouseExited(evt);
            }
        });
        jPanel1.add(excluirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        alterarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alterarFilm.png"))); // NOI18N
        alterarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alterarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alterarBtnMouseExited(evt);
            }
        });
        jPanel1.add(alterarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Filmes:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        idCinemaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("IdCinema"));
        jPanel1.add(idCinemaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 120, -1));

        idFilmeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("IdFilme"));
        idFilmeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFilmeTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(idFilmeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 120, -1));

        designarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/designarFilm.png"))); // NOI18N
        designarBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                designarBtnMouseDragged(evt);
            }
        });
        designarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                designarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                designarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                designarBtnMouseExited(evt);
            }
        });
        jPanel1.add(designarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, -1, -1));

        Fundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundoCinzaDark.png"))); // NOI18N
        jPanel1.add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeFilmeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFilmeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFilmeTextFieldActionPerformed

    private void sinopseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinopseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sinopseTextFieldActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void voltarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarBtnMouseClicked
        // TODO add your handling code here:
         TelaPrincipal telaprincipal = new TelaPrincipal();
        
        
        telaprincipal.emailCache = emailCache;
        telaprincipal.exibirBotao();
        telaprincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarBtnMouseClicked

    private void voltarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarBtnMouseEntered
        // TODO add your handling code here:
        ImageIcon btnVoltar = new ImageIcon(getClass().getResource("/voltarTelas1.png"));
        voltarBtn.setIcon(btnVoltar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        voltarBtn.setCursor(crs);
    }//GEN-LAST:event_voltarBtnMouseEntered

    private void voltarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarBtnMouseExited
        // TODO add your handling code here:
        ImageIcon btnVoltar = new ImageIcon(getClass().getResource("/voltarTelas.png"));
        voltarBtn.setIcon(btnVoltar);
        
    }//GEN-LAST:event_voltarBtnMouseExited

    private void cadastrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarBtnMouseClicked
        // TODO add your handling code here:
        String nomeFilme;
        Integer emCartaz;
        String sinopse;
        String dataLancamento;

        nomeFilme = nomeFilmeTextField.getText();
        emCartaz = Integer.parseInt(emCartazTextField.getText());
        sinopse = sinopseTextField.getText();
        dataLancamento = dataLancamentoTextField.getText();

        if (emCartaz <= 1) {
            Filme filme = new Filme();
            filme.setNomeFilme(nomeFilme);
            filme.setCartaz(emCartaz);
            filme.setSinopse(sinopse);
            filme.setDataLancamento(dataLancamento);

            Administrador adm = new Administrador();
            adm.cadastrarFilme(filme);
            JOptionPane.showMessageDialog(null, "Filme cadastrado com sucesso");
            listarFilmesTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Valor digitado errado");
        }

    }//GEN-LAST:event_cadastrarBtnMouseClicked

    private void cadastrarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarBtnMouseEntered
        // TODO add your handling code here:
        ImageIcon btnCadastrar = new ImageIcon(getClass().getResource("/cadastrarFilm1.png"));
        cadastrarBtn.setIcon(btnCadastrar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        cadastrarBtn.setCursor(crs);
    }//GEN-LAST:event_cadastrarBtnMouseEntered

    private void cadastrarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarBtnMouseExited
        // TODO add your handling code here:
        ImageIcon btnCadastrar = new ImageIcon(getClass().getResource("/cadastrarFilm.png"));
        cadastrarBtn.setIcon(btnCadastrar);
        
    }//GEN-LAST:event_cadastrarBtnMouseExited

    private void alterarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarBtnMouseClicked
        // TODO add your handling code here:
        AlterarFilme();
        listarFilmesTabela();
    }//GEN-LAST:event_alterarBtnMouseClicked

    private void alterarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarBtnMouseEntered
        // TODO add your handling code here:
        ImageIcon btnAlterar = new ImageIcon(getClass().getResource("/alterarFilm1.png"));
        alterarBtn.setIcon(btnAlterar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        alterarBtn.setCursor(crs);
    }//GEN-LAST:event_alterarBtnMouseEntered

    private void alterarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarBtnMouseExited
        // TODO add your handling code here:
        ImageIcon btnAlterar = new ImageIcon(getClass().getResource("/alterarFilm.png"));
        alterarBtn.setIcon(btnAlterar);
    }//GEN-LAST:event_alterarBtnMouseExited

    private void excluirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirBtnMouseClicked
        // TODO add your handling code here:
        ExcluirFilme();
        listarFilmesTabela();
    }//GEN-LAST:event_excluirBtnMouseClicked

    private void excluirBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirBtnMouseEntered
        // TODO add your handling code here:
        ImageIcon btnExcluir = new ImageIcon(getClass().getResource("/excluirFilm1.png"));
        excluirBtn.setIcon(btnExcluir);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        excluirBtn.setCursor(crs);
    }//GEN-LAST:event_excluirBtnMouseEntered

    private void excluirBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirBtnMouseExited
        // TODO add your handling code here:
        ImageIcon btnExcluir = new ImageIcon(getClass().getResource("/excluirFilm.png"));
        excluirBtn.setIcon(btnExcluir);
    }//GEN-LAST:event_excluirBtnMouseExited

    private void idFilmeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFilmeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFilmeTextFieldActionPerformed

    private void designarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_designarBtnMouseClicked
        // TODO add your handling code here:
        Integer idFilme;
        Integer idCine;

        idFilme = Integer.parseInt(idFilmeTextField.getText());
        idCine = Integer.parseInt(idCinemaTextField.getText());

        VincularCinema vincCine = new VincularCinema();
        vincCine.setIdVincFilme(idFilme);
        vincCine.setIdVincCine(idCine);

        DAO dao = new DAO();
        dao.vincularCinema(vincCine);
    }//GEN-LAST:event_designarBtnMouseClicked

    private void designarBtnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_designarBtnMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_designarBtnMouseDragged

    private void designarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_designarBtnMouseEntered
        // TODO add your handling code here:
        ImageIcon btnDesignar = new ImageIcon(getClass().getResource("/designarFilm1.png"));
        designarBtn.setIcon(btnDesignar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        designarBtn.setCursor(crs);
    }//GEN-LAST:event_designarBtnMouseEntered

    private void designarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_designarBtnMouseExited
        // TODO add your handling code here:
        ImageIcon btnDesignar = new ImageIcon(getClass().getResource("/designarFilm.png"));
        designarBtn.setIcon(btnDesignar);
    }//GEN-LAST:event_designarBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarFilmeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarFilmeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarFilmeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarFilmeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarFilmeTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel alterarBtn;
    private javax.swing.JLabel cadastrarBtn;
    private javax.swing.JTable cinemaTable;
    private javax.swing.JTextField dataLancamentoTextField;
    private javax.swing.JLabel designarBtn;
    private javax.swing.JTextField emCartazTextField;
    private javax.swing.JLabel excluirBtn;
    private javax.swing.JTable filmeTable;
    private javax.swing.JTextField idCinemaTextField;
    private javax.swing.JTextField idFilmeTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomeFilmeTextField;
    private javax.swing.JTextField sinopseTextField;
    private javax.swing.JLabel voltarBtn;
    // End of variables declaration//GEN-END:variables

    private void listarFilmesTabela() {
        try {
            DAO dao = new DAO();
            DefaultTableModel model = (DefaultTableModel) filmeTable.getModel();
            model.setNumRows(0);

            ArrayList<Filme> listaFilme = dao.TableFilme();

            for (int num = 0; num < listaFilme.size(); num++) {
                model.addRow(new Object[]{
                    listaFilme.get(num).getId(),
                    listaFilme.get(num).getNomeFilme(),
                    listaFilme.get(num).getCartaz()
                });

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "erro no listarFilmesTabela" + erro);
        }

    }

    private static MouseListener getMouseListener() {
        return new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                System.out.println(((JComponent) e.getSource()).getName());
            }
        };
    }

    private void listarCinemasTabela() {

        cinemaTable.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {

            System.out.println(cinemaTable.getValueAt(cinemaTable.getSelectedRow(), 0).toString());

            String id = cinemaTable.getValueAt(cinemaTable.getSelectedRow(), 0).toString();

            if (id.equals("1")) {
                TelaPrincipal tela = new TelaPrincipal();

                tela.setVisible(true);

                dispose();

            }

        });

        try {
            DAO dao = new DAO();
            DefaultTableModel model = (DefaultTableModel) cinemaTable.getModel();
            model.setNumRows(0);

            ArrayList<Cinema> listaCine = dao.TableCinema();

            for (int num = 0; num < listaCine.size(); num++) {

                model.addRow(new Object[]{
                    listaCine.get(num).getIdCine(),
                    listaCine.get(num).getNomeCinema(),
                    listaCine.get(num).getLocalizacao()
                });

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "erro no listarCinemasTabela" + erro);
        }

    }

    private void AlterarFilme() {
        Integer id;
        String nomeFilme;
        Integer cartaz;
        String sinopse;
        String dataLancamento;

        id = Integer.parseInt(idTextField.getText());
        nomeFilme = nomeFilmeTextField.getText();
        cartaz = Integer.parseInt(emCartazTextField.getText());
        sinopse = sinopseTextField.getText();
        dataLancamento = dataLancamentoTextField.getText();

        Filme filme = new Filme();
        filme.setId(id);
        filme.setNomeFilme(nomeFilme);
        filme.setCartaz(cartaz);
        filme.setSinopse(sinopse);
        filme.setDataLancamento(dataLancamento);

        DAO dao = new DAO();

        dao.alterarFilme(filme);
    }

    private void ExcluirFilme() {
        Integer id;
        id = Integer.parseInt(idTextField.getText());

        Filme filme = new Filme();
        filme.setId(id);

        DAO dao = new DAO();
        dao.excluirFilmeExiste(filme);
        dao.excluirFilme(filme);

    }
}
