/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hickys
 */
public class AdicionarCinemaTela extends javax.swing.JFrame {

    public String emailCache;

    /**
     * Creates new form AdicionarCinema
     */
    public AdicionarCinemaTela() {
        initComponents();
        listarCinemasTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cinemaTable = new javax.swing.JTable();
        idTextField = new javax.swing.JTextField();
        localizacaoTextField = new javax.swing.JTextField();
        nomeCinemaTextField = new javax.swing.JTextField();
        cadastrarBtnCn = new javax.swing.JLabel();
        Voltar = new javax.swing.JLabel();
        excluirBtnCn = new javax.swing.JLabel();
        alterarBtnCn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cinemaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(cinemaTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        idTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("id"));
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, 52));

        localizacaoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Localização"));
        localizacaoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizacaoTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(localizacaoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 260, 60));
        localizacaoTextField.getAccessibleContext().setAccessibleName("Cep");

        nomeCinemaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome do Cinema"));
        nomeCinemaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCinemaTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nomeCinemaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 260, -1));

        cadastrarBtnCn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastrarFilm.png"))); // NOI18N
        cadastrarBtnCn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarBtnCnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarBtnCnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarBtnCnMouseExited(evt);
            }
        });
        jPanel1.add(cadastrarBtnCn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltarTelas.png"))); // NOI18N
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VoltarMouseExited(evt);
            }
        });
        jPanel1.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 640, -1, 30));

        excluirBtnCn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/excluirFilm.png"))); // NOI18N
        excluirBtnCn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirBtnCnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                excluirBtnCnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                excluirBtnCnMouseExited(evt);
            }
        });
        jPanel1.add(excluirBtnCn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        alterarBtnCn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alterarFilm.png"))); // NOI18N
        alterarBtnCn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarBtnCnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alterarBtnCnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alterarBtnCnMouseExited(evt);
            }
        });
        jPanel1.add(alterarBtnCn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Zona Sul - 1        Zona Norte - 2        Zona Leste - 3         Zona Oeste - 4 ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 440, -1));

        Fundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundoCinzaDark.png"))); // NOI18N
        jPanel1.add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localizacaoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizacaoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localizacaoTextFieldActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void nomeCinemaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCinemaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCinemaTextFieldActionPerformed

    private void cadastrarBtnCnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarBtnCnMouseClicked
        // TODO add your handling code here:
        String nomeCinema;
        Integer localizacao;

        nomeCinema = nomeCinemaTextField.getText();
        localizacao = Integer.parseInt(localizacaoTextField.getText());

        if (localizacao < 50) {
            Cinema cine = new Cinema();
            cine.setNomeCinema(nomeCinema);
            cine.setLocalizacao(localizacao);

            Administrador adm = new Administrador();
            adm.adiconarCinema(cine);
        } else {
            JOptionPane.showMessageDialog(null, "Algo deu errado");
        }
    }//GEN-LAST:event_cadastrarBtnCnMouseClicked

    private void cadastrarBtnCnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarBtnCnMouseEntered
        // TODO add your handling code here:
        ImageIcon btnCadastrar = new ImageIcon(getClass().getResource("/cadastrarFilm1.png"));
        cadastrarBtnCn.setIcon(btnCadastrar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        cadastrarBtnCn.setCursor(crs);
    }//GEN-LAST:event_cadastrarBtnCnMouseEntered

    private void cadastrarBtnCnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarBtnCnMouseExited
        // TODO add your handling code here:
        ImageIcon btnCadastrar = new ImageIcon(getClass().getResource("/cadastrarFilm.png"));
        cadastrarBtnCn.setIcon(btnCadastrar);
    }//GEN-LAST:event_cadastrarBtnCnMouseExited

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        // TODO add your handling code here:
        TelaPrincipal telaprincipal = new TelaPrincipal();

        telaprincipal.emailCache = emailCache;
        telaprincipal.exibirBotao();
        telaprincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarMouseClicked

    private void VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseEntered
        // TODO add your handling code here:
        ImageIcon btnVoltar = new ImageIcon(getClass().getResource("/voltarTelas1.png"));
        Voltar.setIcon(btnVoltar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        Voltar.setCursor(crs);
    }//GEN-LAST:event_VoltarMouseEntered

    private void VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseExited
        // TODO add your handling code here:
         ImageIcon btnVoltar = new ImageIcon(getClass().getResource("/voltarTelas.png"));
        Voltar.setIcon(btnVoltar);
    }//GEN-LAST:event_VoltarMouseExited

    private void excluirBtnCnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirBtnCnMouseClicked
        // TODO add your handling code here:
        ExcluirCine();
        listarCinemasTabela();
    }//GEN-LAST:event_excluirBtnCnMouseClicked

    private void excluirBtnCnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirBtnCnMouseEntered
        // TODO add your handling code here:
        ImageIcon btnCadastrar = new ImageIcon(getClass().getResource("/excluirFilm1.png"));
        excluirBtnCn.setIcon(btnCadastrar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        excluirBtnCn.setCursor(crs);
    }//GEN-LAST:event_excluirBtnCnMouseEntered

    private void excluirBtnCnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirBtnCnMouseExited
        // TODO add your handling code here:
        ImageIcon btnCadastrar = new ImageIcon(getClass().getResource("/excluirFilm.png"));
        excluirBtnCn.setIcon(btnCadastrar);
    }//GEN-LAST:event_excluirBtnCnMouseExited

    private void alterarBtnCnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarBtnCnMouseClicked
        // TODO add your handling code here:
        AlterarCine();
        listarCinemasTabela();
    }//GEN-LAST:event_alterarBtnCnMouseClicked

    private void alterarBtnCnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarBtnCnMouseEntered
        // TODO add your handling code here:
         ImageIcon btnAlterar = new ImageIcon(getClass().getResource("/alterarFilm1.png"));
        alterarBtnCn.setIcon(btnAlterar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        alterarBtnCn.setCursor(crs);
    }//GEN-LAST:event_alterarBtnCnMouseEntered

    private void alterarBtnCnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarBtnCnMouseExited
        // TODO add your handling code here:
        ImageIcon btnAlterar = new ImageIcon(getClass().getResource("/alterarFilm.png"));
        alterarBtnCn.setIcon(btnAlterar);
    }//GEN-LAST:event_alterarBtnCnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarCinemaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarCinemaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarCinemaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarCinemaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarCinemaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Voltar;
    private javax.swing.JLabel alterarBtnCn;
    private javax.swing.JLabel cadastrarBtnCn;
    private javax.swing.JTable cinemaTable;
    private javax.swing.JLabel excluirBtnCn;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localizacaoTextField;
    private javax.swing.JTextField nomeCinemaTextField;
    // End of variables declaration//GEN-END:variables

    private void listarCinemasTabela() {

        cinemaTable.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {

            System.out.println(cinemaTable.getValueAt(cinemaTable.getSelectedRow(), 0).toString());

            String id = cinemaTable.getValueAt(cinemaTable.getSelectedRow(), 0).toString();

            if (id.equals("1")) {
                TelaPrincipal tela = new TelaPrincipal();

                tela.setVisible(true);

                dispose();

            }

        });

        try {
            DAO dao = new DAO();
            DefaultTableModel model = (DefaultTableModel) cinemaTable.getModel();
            model.setNumRows(0);

            ArrayList<Cinema> listaCine = dao.TableCinema();

            for (int num = 0; num < listaCine.size(); num++) {

                model.addRow(new Object[]{
                    listaCine.get(num).getIdCine(),
                    listaCine.get(num).getNomeCinema(),
                    listaCine.get(num).getLocalizacao()
                });

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "erro no listarCinemasTabela" + erro);
        }

    }

    private void AlterarCine() {
        Integer id;
        String nomeCinema;
        Integer localizacao;

        nomeCinema = nomeCinemaTextField.getText();
        localizacao = Integer.parseInt(localizacaoTextField.getText());
        id = Integer.parseInt(idTextField.getText());

        Cinema cine = new Cinema();
        cine.setIdCine(id);
        cine.setNomeCinema(nomeCinema);
        cine.setLocalizacao(localizacao);

        DAO dao = new DAO();

        dao.alterarCinema(cine);
        ;
    }

    private void ExcluirCine() {
        Integer id;
        id = Integer.parseInt(idTextField.getText());

        Cinema cine = new Cinema();
        cine.setIdCine(id);

        DAO dao = new DAO();
        dao.excluirCinemaExiste(cine);
        dao.excluirCinema(cine);
    }
}
