/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hickys
 */
public class AdicionarCinemaTela extends javax.swing.JFrame {

    public String emailCache;

    /**
     * Creates new form AdicionarCinema
     */
    public AdicionarCinemaTela() {
        initComponents();
        listarCinemasTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeCinemaTextField = new javax.swing.JTextField();
        localizacaoTextField = new javax.swing.JTextField();
        cadastrarCinemaJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cinemaTable = new javax.swing.JTable();
        idTextField = new javax.swing.JTextField();
        alterarButton = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        VoltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeCinemaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome do Cinema"));

        localizacaoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Localização"));

        cadastrarCinemaJButton.setText("Cadastrar Cinema");
        cadastrarCinemaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCinemaJButtonActionPerformed(evt);
            }
        });

        cinemaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(cinemaTable);

        idTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("id"));

        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarButtonActionPerformed(evt);
            }
        });

        excluirButton.setText("Excluir");
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        VoltarButton.setText("Voltar");
        VoltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cadastrarCinemaJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(nomeCinemaTextField)
                    .addComponent(localizacaoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(alterarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(excluirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(idTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VoltarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeCinemaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(localizacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(cadastrarCinemaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(alterarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(excluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(VoltarButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarCinemaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCinemaJButtonActionPerformed
        // TODO add your handling code here:
        String nomeCinema;
        Integer localizacao;

        nomeCinema = nomeCinemaTextField.getText();
        localizacao = Integer.parseInt(localizacaoTextField.getText());

        if (localizacao < 50) {
            Cinema cine = new Cinema();
            cine.setNomeCinema(nomeCinema);
            cine.setLocalizacao(localizacao);

            Administrador adm = new Administrador();
            adm.adiconarCinema(cine);
        } else {
            JOptionPane.showMessageDialog(null, "Algo deu errado");
        }

    }//GEN-LAST:event_cadastrarCinemaJButtonActionPerformed

    private void alterarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarButtonActionPerformed
        // TODO add your handling code here:
        AlterarCine();
        listarCinemasTabela();
    }//GEN-LAST:event_alterarButtonActionPerformed

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed
        // TODO add your handling code here:

        ExcluirCine();
        listarCinemasTabela();
    }//GEN-LAST:event_excluirButtonActionPerformed

    private void VoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarButtonActionPerformed
        TelaPrincipal telaprincipal = new TelaPrincipal();

        telaprincipal.emailCache = emailCache;
        telaprincipal.exibirBotao();
        telaprincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarCinemaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarCinemaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarCinemaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarCinemaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarCinemaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VoltarButton;
    private javax.swing.JButton alterarButton;
    private javax.swing.JButton cadastrarCinemaJButton;
    private javax.swing.JTable cinemaTable;
    private javax.swing.JButton excluirButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localizacaoTextField;
    private javax.swing.JTextField nomeCinemaTextField;
    // End of variables declaration//GEN-END:variables

    private void listarCinemasTabela() {

        cinemaTable.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {

            System.out.println(cinemaTable.getValueAt(cinemaTable.getSelectedRow(), 0).toString());

            String id = cinemaTable.getValueAt(cinemaTable.getSelectedRow(), 0).toString();

            if (id.equals("1")) {
                TelaPrincipal tela = new TelaPrincipal();

                tela.setVisible(true);

                dispose();

            }

        });

        try {
            DAO dao = new DAO();
            DefaultTableModel model = (DefaultTableModel) cinemaTable.getModel();
            model.setNumRows(0);

            ArrayList<Cinema> listaCine = dao.TableCinema();

            for (int num = 0; num < listaCine.size(); num++) {

                model.addRow(new Object[]{
                    listaCine.get(num).getIdCine(),
                    listaCine.get(num).getNomeCinema(),
                    listaCine.get(num).getLocalizacao()
                });

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "erro no listarCinemasTabela" + erro);
        }

    }

    private void AlterarCine() {
        Integer id;
        String nomeCinema;
        Integer localizacao;

        nomeCinema = nomeCinemaTextField.getText();
        localizacao = Integer.parseInt(localizacaoTextField.getText());
        id = Integer.parseInt(idTextField.getText());

        Cinema cine = new Cinema();
        cine.setIdCine(id);
        cine.setNomeCinema(nomeCinema);
        cine.setLocalizacao(localizacao);

        DAO dao = new DAO();

        dao.alterarCinema(cine);
        ;
    }

    private void ExcluirCine() {
        Integer id;
        id = Integer.parseInt(idTextField.getText());

        Cinema cine = new Cinema();
        cine.setIdCine(id);

        DAO dao = new DAO();
        dao.excluirCinemaExiste(cine);
        dao.excluirCinema(cine);
    }
}
