/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

import java.awt.Cursor;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jvcal
 */
public class CadastroTela extends javax.swing.JFrame {

    
    /**
     * Creates new form CadastroTela
     */
    public CadastroTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeUsuarioTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cepTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        senhaTextField = new javax.swing.JPasswordField();
        Voltar = new javax.swing.JLabel();
        cadastrarBtnTela = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Criar Conta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome de usuário:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        nomeUsuarioTextField.setToolTipText("");
        nomeUsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeUsuarioTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nomeUsuarioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 330, 34));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("E-mail:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 330, 34));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CEP:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        cepTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(cepTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 330, 34));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Senha:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        senhaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(senhaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 330, 47));

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltarTelas.png"))); // NOI18N
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VoltarMouseExited(evt);
            }
        });
        jPanel1.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        cadastrarBtnTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadastrarFilm.png"))); // NOI18N
        cadastrarBtnTela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarBtnTelaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarBtnTelaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarBtnTelaMouseExited(evt);
            }
        });
        jPanel1.add(cadastrarBtnTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        Fundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundoCinzaDark.png"))); // NOI18N
        jPanel1.add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int local;
    private void nomeUsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeUsuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeUsuarioTextFieldActionPerformed

    private void cepTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepTextFieldActionPerformed

    private void senhaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        // TODO add your handling code here:
        LoginTela logintela = new LoginTela();
        
        logintela.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarMouseClicked

    private void VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseEntered
        // TODO add your handling code here:]
        ImageIcon btnVoltar = new ImageIcon(getClass().getResource("/voltarTelas1.png"));
        Voltar.setIcon(btnVoltar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        Voltar.setCursor(crs);
    }//GEN-LAST:event_VoltarMouseEntered

    private void VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseExited
        // TODO add your handling code here:
        ImageIcon btnVoltar = new ImageIcon(getClass().getResource("/voltarTelas.png"));
        Voltar.setIcon(btnVoltar);
    }//GEN-LAST:event_VoltarMouseExited

    private void cadastrarBtnTelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarBtnTelaMouseClicked
        // TODO add your handling code here:
        Cadastro();
    }//GEN-LAST:event_cadastrarBtnTelaMouseClicked

    private void cadastrarBtnTelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarBtnTelaMouseEntered
        // TODO add your handling code here:
        ImageIcon btnCadastrar = new ImageIcon(getClass().getResource("/cadastrarFilm1.png"));
        cadastrarBtnTela.setIcon(btnCadastrar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        cadastrarBtnTela.setCursor(crs);
    }//GEN-LAST:event_cadastrarBtnTelaMouseEntered

    private void cadastrarBtnTelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarBtnTelaMouseExited
        // TODO add your handling code here:
         ImageIcon btnCadastrar = new ImageIcon(getClass().getResource("/cadastrarFilm.png"));
        cadastrarBtnTela.setIcon(btnCadastrar);
    }//GEN-LAST:event_cadastrarBtnTelaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTela().setVisible(true);
            }
        });
    }

    public static boolean isBetween(int x, int lower, int upper) {
        return lower <= x && x <= upper;
    }

    public void Cadastro() {
        Usuario usuarioLogin = new Usuario();
        TelaPrincipal telaprincipal = new TelaPrincipal();
        try {
            String email, senha, nomeUsuario;
            Integer cep;

            email = emailTextField.getText();
            senha = new String(senhaTextField.getPassword());
            cep = Integer.parseInt(cepTextField.getText());
            nomeUsuario = nomeUsuarioTextField.getText();
            String adm = "0";

            // atribui os 
            usuarioLogin.setEmail(email);
            usuarioLogin.setSenha(senha);
            usuarioLogin.setCep(cep);
            usuarioLogin.setNomeUsuario(nomeUsuario);
            usuarioLogin.setAdministrador(adm);

            DAO autenticacao = new DAO();

            ResultSet rsUsuarioValidoCad = autenticacao.autenticacaoCadastro(usuarioLogin);
            if (rsUsuarioValidoCad.next()) {
                JOptionPane.showMessageDialog(null, "Email já existente");
            } else if (email.isBlank() || senha.isBlank() || cep == null || nomeUsuario.isBlank()) {
                JOptionPane.showMessageDialog(null, "Campos inválidos");

            } else {

                if (isBetween(cep, 1,999999)) {
                    JOptionPane.showMessageDialog(null, "Cep Invalido");
                    return;

                } // Zona Sul
                else if (isBetween(cep, 4000000, 4999999)) {
                    local = 1;
                    usuarioLogin.setLocal(local);
                    System.out.println(local);
                } // Zona norte
                else if (isBetween(cep, 2000000, 2999999)) {
                    local = 2;
                    usuarioLogin.setLocal(local);
                    System.out.println(local);

                    // Zona Leste
                } else if (isBetween(cep, 3000000, 3999999)) {
                    local = 3;
                    usuarioLogin.setLocal(local);
                    System.out.println(local);
                } else if (isBetween(cep, 8000000, 8499999)) {
                    local = 3;
                    usuarioLogin.setLocal(local);
                    System.out.println(local);
                } //Zona Oeste
                else if (isBetween(cep, 5000000, 5899999)) {
                    local = 4;
                    usuarioLogin.setLocal(local);
                    System.out.println(local);
                } // Zona Central
                else if (isBetween(cep, 1000000, 1599999)) {
                    local = 5;
                    usuarioLogin.setLocal(local);
                    System.out.println(local);

                } else {
                    System.out.println("Algo deu errado");

                }
                autenticacao.CadastrarUsuario(usuarioLogin);
                autenticacao.armazenarDados(usuarioLogin);
                telaprincipal.emailCache = usuarioLogin.getEmail();
                telaprincipal.setVisible(true);
                dispose();

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Cadastro Tela: " + erro);
        };

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Voltar;
    private javax.swing.JLabel cadastrarBtnTela;
    private javax.swing.JTextField cepTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeUsuarioTextField;
    private javax.swing.JPasswordField senhaTextField;
    // End of variables declaration//GEN-END:variables
}
