/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

import static com.mycompany.cinema.CadastroTela.isBetween;
import javax.swing.JOptionPane;

/**
 *
 * @author Hickys
 */
public class EditarPefilTela extends javax.swing.JFrame {

    String emailCache;
    Integer local;

    /**
     * Creates new form EditarPefilTela
     */
    public EditarPefilTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailTextField = new javax.swing.JTextField();
        cepTextField = new javax.swing.JTextField();
        alterarButton = new javax.swing.JButton();
        nomeUsuarioTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        senhaTextField = new javax.swing.JTextField();
        VoltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emailTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Email:"));

        cepTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("CEP:"));

        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarButtonActionPerformed(evt);
            }
        });

        nomeUsuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome de Usuário:"));

        idLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("ID:"));

        senhaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha:"));

        VoltarButton.setText("Voltar");
        VoltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cepTextField)
                                .addComponent(nomeUsuarioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alterarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VoltarButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alterarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(VoltarButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alterarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarButtonActionPerformed
        // TODO add your handling code here:
        AlterarUsuario();
    }//GEN-LAST:event_alterarButtonActionPerformed

    private void VoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarButtonActionPerformed
        PerfilTela perfiltela = new PerfilTela();
        perfiltela.emailCache = emailCache;
        perfiltela.exibirDados();
        perfiltela.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPefilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPefilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPefilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPefilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPefilTela().setVisible(true);
            }
        });
    }

    public void exibirDadosEditar() {
        Usuario usuario = new Usuario();
        DAO dao = new DAO();
        usuario.setEmail(emailCache);

        dao.armazenarDados(usuario);
        nomeUsuarioTextField.setText(usuario.getNomeUsuario());
        cepTextField.setText(String.valueOf(usuario.getCep()));
        emailTextField.setText(usuario.getEmail());
        senhaTextField.setText(usuario.getSenha());
        idLabel.setText(String.valueOf(usuario.getId()));

    }

    private void AlterarUsuario() {
        String email;
        String nomeUsuario;
        Integer cep;
        String senha;
        Integer id;
        email = emailTextField.getText();
        nomeUsuario = nomeUsuarioTextField.getText();
        cep = Integer.parseInt(cepTextField.getText());
        senha = senhaTextField.getText();
        id = Integer.parseInt(idLabel.getText());

        Usuario usu = new Usuario();

        DAO dao = new DAO();

        if (nomeUsuario.isBlank() || cep == null || senha.isBlank() || email.isBlank()) {
            JOptionPane.showMessageDialog(null, "Campos inválidos");
        } else {
            
            if (isBetween(cep, 1, 999999)) {
                JOptionPane.showMessageDialog(null, "Cep Invalido");
                return;

            } // Zona Sul
            else if (isBetween(cep, 4000000, 4999999)) {
                local = 1;
                usu.setLocal(local);
                System.out.println(local);
            } // Zona norte
            else if (isBetween(cep, 2000000, 2999999)) {
                local = 2;
                usu.setLocal(local);
                System.out.println(local);

                // Zona Leste
            } else if (isBetween(cep, 3000000, 3999999)) {
                local = 3;
                usu.setLocal(local);
                System.out.println(local);
            } else if (isBetween(cep, 8000000, 8499999)) {
                local = 3;
                usu.setLocal(local);
                System.out.println(local);
            } //Zona Oeste
            else if (isBetween(cep, 5000000, 5899999)) {
                local = 4;
                usu.setLocal(local);
                System.out.println(local);
            } // Zona Central
            else if (isBetween(cep, 1000000, 1599999)) {
                local = 5;
                usu.setLocal(local);
                System.out.println(local);

            } else {
                System.out.println("Algo deu errado");

            }
            usu.setEmail(email);
            usu.setNomeUsuario(nomeUsuario);
            usu.setCep(cep);
            usu.setSenha(senha);
            usu.setId(id);
            dao.alterarUsuario(usu);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VoltarButton;
    private javax.swing.JButton alterarButton;
    private javax.swing.JTextField cepTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField nomeUsuarioTextField;
    private javax.swing.JTextField senhaTextField;
    // End of variables declaration//GEN-END:variables
}
