/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

import static com.mycompany.cinema.CadastroTela.isBetween;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hickys
 */
public class EditarPefilTela extends javax.swing.JFrame {

    String emailCache;
    Integer local;

    /**
     * Creates new form EditarPefilTela
     */
    public EditarPefilTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        nomeUsuarioTextField = new javax.swing.JTextField();
        cepTextField = new javax.swing.JTextField();
        senhaTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        Voltar = new javax.swing.JLabel();
        alterarPerfilBtn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        idLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("ID:"));
        idLabel.setOpaque(true);
        jPanel1.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, 52));

        nomeUsuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome de Usuário:"));
        nomeUsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeUsuarioTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nomeUsuarioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 330, 50));

        cepTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("CEP:"));
        cepTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(cepTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 154, 62));

        senhaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha:"));
        senhaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(senhaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 154, 66));

        emailTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Email:"));
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 154, 55));

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltarTelas.png"))); // NOI18N
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VoltarMouseExited(evt);
            }
        });
        jPanel1.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        alterarPerfilBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alterarFilm.png"))); // NOI18N
        alterarPerfilBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarPerfilBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alterarPerfilBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alterarPerfilBtnMouseExited(evt);
            }
        });
        jPanel1.add(alterarPerfilBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 170, 100, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editar Perfil");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 30));

        Fundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundoCinzaDark.png"))); // NOI18N
        jPanel1.add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cepTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepTextFieldActionPerformed

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        // TODO add your handling code here:
        PerfilTela perfiltela = new PerfilTela();
        perfiltela.emailCache = emailCache;
        perfiltela.exibirDados();
        perfiltela.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarMouseClicked

    private void VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseEntered
        // TODO add your handling code here:
        ImageIcon btnVoltar = new ImageIcon(getClass().getResource("/voltarTelas1.png"));
        Voltar.setIcon(btnVoltar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        Voltar.setCursor(crs);
    }//GEN-LAST:event_VoltarMouseEntered

    private void VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseExited
        // TODO add your handling code here:
        ImageIcon btnVoltar = new ImageIcon(getClass().getResource("/voltarTelas.png"));
        Voltar.setIcon(btnVoltar);
    }//GEN-LAST:event_VoltarMouseExited

    private void senhaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void nomeUsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeUsuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeUsuarioTextFieldActionPerformed

    private void alterarPerfilBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarPerfilBtnMouseClicked
        // TODO add your handling code here:
        AlterarUsuario();
    }//GEN-LAST:event_alterarPerfilBtnMouseClicked

    private void alterarPerfilBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarPerfilBtnMouseEntered
        // TODO add your handling code here:
        ImageIcon btnAlterar = new ImageIcon(getClass().getResource("/alterarFilm1.png"));
        alterarPerfilBtn.setIcon(btnAlterar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        alterarPerfilBtn.setCursor(crs);
    }//GEN-LAST:event_alterarPerfilBtnMouseEntered

    private void alterarPerfilBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarPerfilBtnMouseExited
        // TODO add your handling code here:
        ImageIcon btnAlterar = new ImageIcon(getClass().getResource("/alterarFilm.png"));
        alterarPerfilBtn.setIcon(btnAlterar);
    }//GEN-LAST:event_alterarPerfilBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPefilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPefilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPefilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPefilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPefilTela().setVisible(true);
            }
        });
    }

    public void exibirDadosEditar() {
        Usuario usuario = new Usuario();
        DAO dao = new DAO();
        usuario.setEmail(emailCache);

        dao.armazenarDados(usuario);
        nomeUsuarioTextField.setText(usuario.getNomeUsuario());
        cepTextField.setText(String.valueOf(usuario.getCep()));
        emailTextField.setText(usuario.getEmail());
        senhaTextField.setText(usuario.getSenha());
        idLabel.setText(String.valueOf(usuario.getId()));

    }

    private void AlterarUsuario() {
        String email;
        String nomeUsuario;
        Integer cep;
        String senha;
        Integer id;
        email = emailTextField.getText();
        nomeUsuario = nomeUsuarioTextField.getText();
        cep = Integer.parseInt(cepTextField.getText());
        senha = senhaTextField.getText();
        id = Integer.parseInt(idLabel.getText());

        Usuario usu = new Usuario();

        DAO dao = new DAO();

        if (nomeUsuario.isBlank() || cep == null || senha.isBlank() || email.isBlank()) {
            JOptionPane.showMessageDialog(null, "Campos inválidos");
        } else {
            
            if (isBetween(cep, 1, 999999)) {
                JOptionPane.showMessageDialog(null, "Cep Invalido");
                return;

            } // Zona Sul
            else if (isBetween(cep, 4000000, 4999999)) {
                local = 1;
                usu.setLocal(local);
                System.out.println(local);
            } // Zona norte
            else if (isBetween(cep, 2000000, 2999999)) {
                local = 2;
                usu.setLocal(local);
                System.out.println(local);

                // Zona Leste
            } else if (isBetween(cep, 3000000, 3999999)) {
                local = 3;
                usu.setLocal(local);
                System.out.println(local);
            } else if (isBetween(cep, 8000000, 8499999)) {
                local = 3;
                usu.setLocal(local);
                System.out.println(local);
            } //Zona Oeste
            else if (isBetween(cep, 5000000, 5899999)) {
                local = 4;
                usu.setLocal(local);
                System.out.println(local);
            } // Zona Central
            else if (isBetween(cep, 1000000, 1599999)) {
                local = 5;
                usu.setLocal(local);
                System.out.println(local);

            } else {
                System.out.println("Algo deu errado");

            }
            usu.setEmail(email);
            usu.setNomeUsuario(nomeUsuario);
            usu.setCep(cep);
            usu.setSenha(senha);
            usu.setId(id);
            dao.alterarUsuario(usu);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Voltar;
    private javax.swing.JLabel alterarPerfilBtn;
    private javax.swing.JTextField cepTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeUsuarioTextField;
    private javax.swing.JTextField senhaTextField;
    // End of variables declaration//GEN-END:variables
}
