/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema;

import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hickys
 */
public class PerfilTela extends javax.swing.JFrame {

    String emailCache;

    /**
     * Creates new form PerfilTela
     */
    public PerfilTela() {
        initComponents();

    }

    public void Mostrar() {
        Usuario usu = new Usuario();
        String nomeUsuario = usu.getNomeUsuario();

        nomeUsuarioLabel.setText(nomeUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cepLabel = new javax.swing.JLabel();
        nomeUsuarioLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        Cabeçalho = new javax.swing.JLabel();
        Voltar = new javax.swing.JLabel();
        editarBtn = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cepLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cep:"));
        cepLabel.setOpaque(true);
        jPanel1.add(cepLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, 60));

        nomeUsuarioLabel.setToolTipText("");
        nomeUsuarioLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        nomeUsuarioLabel.setOpaque(true);
        jPanel1.add(nomeUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 330, 60));

        emailLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        emailLabel.setOpaque(true);
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 330, 60));

        idLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("ID:"));
        idLabel.setOpaque(true);
        jPanel1.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 160, 60));

        Cabeçalho.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Cabeçalho.setForeground(new java.awt.Color(255, 255, 255));
        Cabeçalho.setText("Perfil");
        jPanel1.add(Cabeçalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltarTelas.png"))); // NOI18N
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VoltarMouseExited(evt);
            }
        });
        jPanel1.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        editarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editarPerfil.png"))); // NOI18N
        editarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editarBtnMouseExited(evt);
            }
        });
        jPanel1.add(editarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        Fundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundoCinzaDark.png"))); // NOI18N
        jPanel1.add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        // TODO add your handling code here:
        TelaPrincipal telaprincipal = new TelaPrincipal();

        telaprincipal.emailCache = emailCache;
        telaprincipal.exibirBotao();
        telaprincipal.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_VoltarMouseClicked

    private void VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseEntered
        // TODO add your handling code here:
        ImageIcon btnVoltar = new ImageIcon(getClass().getResource("/voltarTelas1.png"));
        Voltar.setIcon(btnVoltar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        Voltar.setCursor(crs);
        
    }//GEN-LAST:event_VoltarMouseEntered

    private void VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseExited
        // TODO add your handling code here:
        ImageIcon btnVoltar = new ImageIcon(getClass().getResource("/voltarTelas.png"));
        Voltar.setIcon(btnVoltar);
    }//GEN-LAST:event_VoltarMouseExited

    private void editarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtnMouseClicked
        // TODO add your handling code here:
        EditarPefilTela editar = new EditarPefilTela();
        editar.emailCache = emailCache;

        editar.exibirDadosEditar();
        System.out.println("email cache tela perfil editar:" + editar.emailCache);

        editar.setVisible(true);
        dispose();
    }//GEN-LAST:event_editarBtnMouseClicked

    private void editarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtnMouseEntered
        // TODO add your handling code here:
        ImageIcon btnEditar = new ImageIcon(getClass().getResource("/editarPerfil1.png"));
        editarBtn.setIcon(btnEditar);
        Cursor crs = new Cursor(Cursor.HAND_CURSOR);
        editarBtn.setCursor(crs);
    }//GEN-LAST:event_editarBtnMouseEntered

    private void editarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBtnMouseExited
        // TODO add your handling code here:
        ImageIcon btnEditar = new ImageIcon(getClass().getResource("/editarPerfil.png"));
        editarBtn.setIcon(btnEditar);
    }//GEN-LAST:event_editarBtnMouseExited

    public void exibirDados() {
        Usuario usuario = new Usuario();
        DAO dao = new DAO();
        usuario.setEmail(emailCache);
        System.out.println("id tela perfil :" + usuario.getId());
        dao.armazenarDados(usuario);
        cepLabel.setText(String.valueOf("0" + usuario.getCep()));
        nomeUsuarioLabel.setText(usuario.getNomeUsuario());
        emailLabel.setText(usuario.getEmail());
        idLabel.setText(String.valueOf(usuario.getId()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cabeçalho;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Voltar;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JLabel editarBtn;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeUsuarioLabel;
    // End of variables declaration//GEN-END:variables
}
